# Site settings
title: ğŸ› ï¸ radiator ğŸ› ï¸
description: A radixDLT based project node.
url: "http://www.radiator.run" # the base hostname & protocol for your site
# baseurl: "" # the subpath of your site, e.g. /blog

# User settings
username: ğŸ› ï¸ radiator ğŸ› ï¸
email: info@radiator.run

# Global settings
icon_size: 58

# Google analytics tracking ID
google_analytics_tracking_id: UA-223301828-1

plugins:
  - jekyll-seo-tag
  